### ISSUE TITLE
Add configuration to turn off ic

### ISSUE THREAD

**Issue by IVBakker** [gruns/icecream#10]
It would be good to have an option to turn off all ic calls based on a config option.

Basically when developping you can use ic but in it's too much of a debug tool to be used in production. Thus the production configuration would have all ic turned off (a bit like logging level in production).

**Comment by gruns** [comment]
`ic.enable()` and `ic.disable()` added in v1.1.

```python
from icecream import ic

ic(1)

ic.disable()
ic(2)

ic.enable()
ic(3)
```

prints

```
ic| 1: 1
ic| 3: 3
```

Upgrade with

```
pip install icecream --upgrade
```

Thank you for your great idea, Luigi. Don't hesitate to let me know if there's anything else I can do for you.
