### ISSUE TITLE
getting NoSourceAvailableError in middle of debug

### ISSUE THREAD

**Issue by vp-31** [gruns/icecream#101]
-> whenever i m debugging i m sometimes i am getting NoSourceAvailableError(). Without debug it is running smoothly
below is error in detail:
<class 'icecream.icecream.NoSourceAvailableError'>, NoSourceAvailableError(), <traceback object at 0x7fca0e01c488>

-> i am using code "logger.debug(ic.format())"
where **logger** is object of '**logging**' python library
logger is kept as global variable and is called frequently

-> i m using IDE: pycharm

**Comment by gruns** [comment]
> whenever i m debugging i m sometimes i am getting NoSourceAvailableError(). Without debug it is running smoothly

are you modifying the program's source code while the program is running? if so, that's why this error will appear

see the error in full: https://github.com/gruns/icecream/blob/master/icecream/icecream.py#L92-L110

```python
class NoSourceAvailableError(OSError):
    """
    Raised when icecream fails to find or access source code that's
    required to parse and analyze. This can happen, for example, when

      - ic() is invoked inside a REPL or interactive shell, e.g. from the
        command line (CLI) or with python -i.

      - The source code is mangled and/or packaged, e.g. with a project
        freezer like PyInstaller.

      - The underlying source code changed during execution. See
        https://stackoverflow.com/a/33175832.
    """
    infoMessage = (
        'Failed to access the underlying source code for analysis. Was ic() '
        'invoked in a REPL (e.g. from the command line), a frozen application '
        '(e.g. packaged with PyInstaller), or did the underlying source code '
        'change during execution?')
```
