### ISSUE TITLE
Emoji prefix inconsistent whitespace 

### ISSUE THREAD

**Issue by Mathemmagician** [gruns/icecream#104]
Fun issue I'm 👁bserving. Trying to use emojis as prefix makes lines 2+ a bit inconsistent (shifted back by 1 space). 

Setup: Jupyter Lab, macOS Catalina

```
from icecream import ic
ic.configureOutput(outputFunction=print,  prefix='👁 👁 ')

random_text = 'First very long text'
random_text2 = 'Second very long text'
random_text3 = 'Third very long text'

ic(random_text, random_text2, random_text3)
```

<img width="501" alt="Screen Shot 2021-08-09 at 2 50 46 PM" src="https://user-images.githubusercontent.com/42552279/128758442-ae994166-7958-4640-a580-a26884395b64.png">

Using a prefix without emojis: 

<img width="518" alt="Screen Shot 2021-08-09 at 2 51 30 PM" src="https://user-images.githubusercontent.com/42552279/128758527-39bb7f65-bf7f-405b-b74c-25c88aff5e9b.png">

**Comment by alexmojaki** [comment]
```
👁️abc
Xabc
```

I think it's just that the fixed width font doesn't render emojis in the fixed width

**Comment by Mathemmagician** [comment]
Interesting. I guess I need fixed width emojis?

**Comment by alexmojaki** [comment]
i think you need to not use emojis lol

**Comment by Mathemmagician** [comment]
Not using emojis in 2021? Not gonna happen lol. I think I'll just live with this inconsistency.

For the reference, I'm using "👁 👁 " to indicate information that needs to be double checked in the notebook, which makes the output really standout. So the use case is pretty legit

**Comment by alexmojaki** [comment]
```python
from icecream import ic
ic.configureOutput(outputFunction=print)

random_text = 'First very long text'
random_text2 = 'Second very long text'
random_text3 = 'Third very long text'

ic('👁', random_text, random_text2, random_text3)
```

```
ic| '👁': '👁'
    random_text: 'First very long text'
    random_text2: 'Second very long text'
    random_text3: 'Third very long text'
```

Literals are actually only supposed to be shown once but that doesn't work with multiline output (https://github.com/gruns/icecream/issues/84). In this case it works out OK though lol

**Comment by Mathemmagician** [comment]
> ic| '👁': '👁'

That's funny!

**Comment by gruns** [comment]
> For the reference, I'm using "eye eye " to indicate information that needs to be double checked in the notebook, which makes the output really standout.

that's cute 😊. i like it
