### ISSUE TITLE
redirect in linux not working

### ISSUE THREAD

**Issue by itnygr2** [gruns/icecream#105]
os:ubuntu 18.04
python version: 3.7.11
when i write something like ```ic('hello')``` and save it to a file named, say, ```hello.py``` and redirect its output using ```python3 hello.py > hello.txt```, the ouptut still prints on the terminal and hello.txt is empty.

is there anyway to get around this behavior on my environment? thanks.

**Comment by alexmojaki** [comment]
`>` redirects stdout, ic uses stderr by default. You can redirect stderr with `2>` or use `ic.configureOutput(outputFunction=print)` to make it use stdout.

**Comment by gruns** [comment]
@itnygr2 do alex's suggestions work for you? if so, ill close this issue. thank you! 🙌 

@alexmojaki my first thought was a worry that our docs dont mention stderr. but i just sanity checked and they do. if other users get confused by stderr vs stdout in the future, too, we can tweak the docs so its more discoverable
