### ISSUE TITLE
Using ic to print list but in 1 line?

### ISSUE THREAD

**Issue by DeadBush225** [gruns/icecream#107]
I have a very long list consisting of 30 items and ic is printing it vertically. Is there anyway to make ic print list horizontally?

when printing my list:
ic| per_picture: [[' ',
                   'b',
                   ' ',
                   'c',
                   ' ',
                   'd',
                   ' ',
                   'e',
                   ' ',
                   'f',
                   ' ',
                   'g',
                   ' ',
                   'h',
                   ' ',
                   'i',
                   ' ',
                   'j',
                   ' ',
                   'k',
                   ' ',
                   'l',
                   ' ',
                   'm',
                   ' ',
                   'n',
                   ' ',
                   'o',
                   ' ',
                   'p',
                   ' ',
                   'q',
                   ' ',
                   'r',
                   ' ',
                   's',
                   ' ',
                   't',
                   ' ',
                   'u',
                   ' ',
                   'v',
                   ' ',
                   'w',
                   ' ',
                   'x',
                   ' ',
                   'y',
                   ' ',
                   'z',
                   ' ',
                   '
                 
                 '],
                  [' ',
                   'b',
                   ' ',
                   'c',
                   ' ',
                   'd',
                   ' ',
                   'e',
                   ' ',
                   'f',
                   ' ',
                   'g',
                   ' ',
                   'h',
                   ' ',
                   'i',
                   ' ',
                   'j',
                   ' ',
                   'k',
                   ' ',
                   'l',
                   ' ',
                   'm',
                   ' ',
                   'n',
                   ' ',
                   'o',
                   ' ',
                   'p',
                   ' ',
                   'q',
                   ' ',
                   'r',
                   ' ',
                   's',
                   ' ',
                   't',
                   ' ',
                   'u',
                   ' ',
                   'v',
                   ' ',
                   'w',
                   ' ',
                   'x',
                   ' ',
                   'y',
                   ' ',
                   'z',
                   ' ',
                   '
                 
                 ']]

**Comment by alexmojaki** [comment]
See https://github.com/gruns/icecream#configuration. `ic.configureOutput(argToStringFunction=repr)` should do.

**Comment by DeadBush225** [comment]
You helped me, Thank you!
