### ISSUE TITLE
somehow doesn't work in jupyter notebook

### ISSUE THREAD

**Issue by pandahop** [gruns/icecream#108]
![image](https://user-images.githubusercontent.com/88259121/135699821-99ccd657-c5ce-45ab-af0f-91da0dd0322e.png)
when i do ic(a) independently in a cell it works. when i do it in a cell with display function it works. if i don't add str function the first ic call in screenshot fails. if i add it the second one fails. this screenshot is taken from kaggle notebook, using fashion mnist's data.

**Comment by alexmojaki** [comment]
The combination of IPython and putting multiple statements on one line using `;` is giving `executing` trouble. A fix is coming in https://github.com/alexmojaki/executing/pull/29 but in general avoid the combination of `;`, IPython, and icecream. So just putting `ic(train.shape, test.shape)` on its own separate line should be enough.

**Comment by alexmojaki** [comment]
Released a fix. `pip install -U executing`, make sure that `import executing; executing.__version__` gives `0.8.2`, and then try again.

**Comment by gruns** [comment]
sounds good 👍
