### ISSUE TITLE
No Reply from arc.io

### ISSUE THREAD

**Issue by PBhadoo** [gruns/icecream#123]
I'm trying to reach arc.io team from 6 months. Getting no replies.

**Comment by gruns** [comment]
this is an open source project, not arc.io support

email team@arc.io and include 'PBhadoo' in the email subject

**Comment by Deshdeepak1** [comment]
I had emailed [team@arc.io](mailto:team@arc.io) for 2 years constantly and never got a reply . Now even the website is down. Are you a scammer ?
