### ISSUE TITLE
Could add option to disable pretty_print?

### ISSUE THREAD

**Issue by rocke2020** [gruns/icecream#124]
Sometimes, pretty print is good. But sometimes, we really don't need pretty print, but the default print format.
I checked and find there is not a option to simply disable pretty print in icecream.
Could add option to disable pretty_print?

I use icecream frequently and thanks for very much for authors.
Thanks!!!

**Comment by gruns** [comment]
pretty printing gets applied in the `ic.argToStringFunction` function, which is customizable via `ic.configureOutput()`. insofar, disabling pretty printing is as easy as supplying your own, replacement `argToStringFunction` function to `ic.configureOutput()` without pretty printing, like `lambda _: str(_)`

example:

```python
>>> from icecream import ic
>>> d = {1:'1'*30, 2:'2'*30, 3:'3'*30}
>>> ic(d)
ic| d: {1: '111111111111111111111111111111',
        2: '222222222222222222222222222222',
        3: '333333333333333333333333333333'}
>>>
>>> ic.configureOutput(argToStringFunction=lambda _: str(_))
>>> ic(d)
ic| d: {1: '111111111111111111111111111111', 2: '222222222222222222222222222222', 3: '333333333333333333333333333333'}
```

does this suffice for your needs? if not, we can think about adding a `prettyPrint=` param, or similar, to `ic.configureOutput()` for better ease of use

if this does suffice for your needs, we can first improve icecream's documentation so others don't get surprised by this behavior

thank you for opening this issue! 🙌

**Comment by rocke2020** [comment]
Dear gruns, your solution is what I need. Thanks!!!
Yes, I think it would be better to add a prettyPrint param into ic.configureOutput(), or similar.
