### ISSUE TITLE
AttributeError: module 'icecream' has no attribute 'configureOutput'

### ISSUE THREAD

**Issue by TsabarM** [gruns/icecream#129]
in the new 2.1.2 version, there is a problem to use the configureOutput attribute. python raising this error:
AttributeError: module 'icecream' has no attribute 'configureOutput'
code: 

import time
from datetime import datetime
import icecream as ic

def time_format():
    return f'{datetime.now()}|> '

ic.configureOutput(prefix=time_format)

**Comment by gruns** [comment]
`configureOutput()` is a method of the `ic` instance. change

```python
import icecream as ic
```

to

```python
from icecream import ic
```
