### ISSUE TITLE
Stack Traces

### ISSUE THREAD

**Issue by 0x5a17ed** [gruns/icecream#14]
Sometimes I would love to see a stack trace as well when calling ic.

**Comment by 0x5a17ed** [comment]
Sorry, I thought a simple description of the feature request would suffice but apparently it wasn't clear enough.

Sometimes it's useful for me to see the call stack together with a value. So every time I want to inspect a value together with a call stack I have to type down:

```python
def baa(foo):
    import traceback; traceback.print_stack(limit=-1)
    from icecream import ic; ic(foo)

baa(42)
```
in order to see what's going on.
```plain
  File "fancy_script.py", line 5, in <module>
    baa(42)
  File "fancy_script.py", line 2, in baa
    import traceback; traceback.print_stack()
ic| foo: 42
```

It would be nice to combine the steps of importing and use of `traceback.print_stack` and icecream in a single line without making my fingers bleed from smashing the keyboard.

**Comment by gruns** [comment]
Thank you for the example! That's extremely helpful.

I can definitely see the utility of such a stack trace in certain situations.
Though it is, perhaps, a bit out of scope and likely better added via a custom
outputFunction (`customizeOutput(outputFunction=...)`. IceCream should aspire to
remain lean, mean, and focused.

That said, to flush out the idea a bit more, would you rather have stack traces
exposed via a `configureOutput()` flag, like

```python
>>> from icecream import ic
>>> ic.configureOutput(includeStackTrace=True)
>>> ic(...)
```

or via a separate new method, like

```python
>>> from icecream import ic
>>> ic.trace(...)
```

?

**Comment by 0x5a17ed** [comment]
This is a harder question than it might seem at a first glance. 

I came to the conclusion that the real question here to answer is whenever I want to inspect the call stack only for certain calls to icecream or have a global switch to see the call stack for all calls into icecream. The latter option I mentioned might be nice to see the stack trace on multiple locations whenever needed but it will clobber the terminal output when there are multiple locations where icecream is used. The former option has the aftertaste of being overly verbose. 

I'm not sure here which option is the better one.

**Comment by gruns** [comment]
Closing this issue, for now, in the default interest of keeping IceCream lean and mean.

If others (i.e. you, future Issue reader) would find stack trace support in IceCream useful, please weigh in and comment here!


Thank you for your wonderful idea, @0x5a17ed. Don't hesitate to let me know if there's anything else I can do for you.

**Comment by Yajo** [comment]
> If others (i.e. you, future Issue reader) would find stack trace support in
> IceCream useful, please weigh in and comment here!

🙋🏼‍♂️ I'm missing this, FWIW.

**Comment by alexmojaki** [comment]
`ic()` on its own is already for the purpose of inspecting execution, I think changing it to show a stack trace would be good.

**Comment by Christophe31** [comment]
It would be nice to have an ic.trace() function to help identify why something is called more than it should…

**Comment by suewonjp** [comment]
Python already has provided most of stack trace functionality and calling that feature would be enough, IMO.
I guess ic can support this feature without adding too much extra code.
 ( That's just my guess which might be wrong, though. My apology if I was wrong. )

The following interface would be cool.
```
>>> from icecream import ic
>>> ic.trace(...)
```
