### ISSUE TITLE
How to only print what is in the parentheses? 

### ISSUE THREAD

**Issue by Nmirabile777** [gruns/icecream#145]
Hi,

I am not sure this is the right place to ask this question, but is there a way to only print what is in the parentheses?

For example,
ic(f'Analyzing Folder: {folder}')

even with prefix set to '' would output,
f'Analyzing Folder: {folder}': 'Analyzing Folder: _xyz_'

Is there a way to only print
'Analyzing Folder: _xyz_'
and maybe an option to remove the '' from what is being printed?

Thank you,
Nick

**Comment by alexmojaki** [comment]
I recommend either:

1. `print(f'Analyzing Folder: {folder}')` or
2. `ic(folder)`

**Comment by Nmirabile777** [comment]
> 

Ok, thank you for your response!
