### ISSUE TITLE
How safe is this module?

### ISSUE THREAD

**Issue by brinza888** [gruns/icecream#163]
This module uses `executing`, which one uses tricks and modifications in AST to detect correct attribute nodes. So how safe are these modifications for runtime and correct execution?

Sorry for opening Issues in both `executing` and `icecream`, maybe this can be useful for issue/questions archive in both of your projects. [My issue in executing module](https://github.com/alexmojaki/executing/issues/77).

**Comment by alexmojaki** [comment]
Responded in the other issue.
