### ISSUE TITLE
Python 2.7 builds are broken

### ISSUE THREAD

**Issue by palfrey** [gruns/icecream#168]
Due to https://github.com/actions/setup-python/issues/672

**Comment by palfrey** [comment]
FYI @gruns still seeing this one on https://github.com/gruns/icecream/commit/a90e838f63887dda02be842413890b504946a1e0. Any thoughts there?

**Comment by gruns** [comment]
hey @palfrey! have you upgraded past python 2.7?

I'm about to drop support for python27 to simplify icecream's code, tests, and dependencies. py27 hit EOL in january 2020, four years ago

**Comment by palfrey** [comment]
Oh, way, way past it. Please drop it!

**Comment by gruns** [comment]
awesome 🙂. thanks @palfrey!
