### ISSUE TITLE
First release.

### ISSUE THREAD

**Issue by inakimalerba** [gruns/icecream#19]
Hi there !.
I'd like to debianize this package, do you have any plans on making a release soon? :smiley: 

Abrazo!

**Comment by gruns** [comment]
I'll wrap a release up for you shortly!

**Comment by gruns** [comment]
v1.3 tagged and released:

  * https://github.com/gruns/icecream/releases/tag/v1.3

Does that suffice for your packaging needs @inakimalerba?

**Comment by inakimalerba** [comment]
Hi there! That's great. 

Closing this issue.
