### ISSUE TITLE
Is there an option to force ic to output regardless of the state of ic.enabled?

### ISSUE THREAD

**Issue by yutaka-uno-nec** [gruns/icecream#197]
I know we can control ic outputs with the state of ic.enabled.
So we can easily get ic outputs when debugging mode only as follows:

```
if __debug__ == True:
    ic.enable()
else:
    ic.disable()
```
However, if we have an option to force ic to output even when ic.enabled=False, it would be very convenient. 
For example, I want to get rich outputs, which ic can provide, when running in non-debugging mode.
I think that now we have to insert enable()/disable() before and after the line where we want the output from ic every time, like as follows:
```
ic.enable()
ic(something)
ic.disable()
```

Is there a way to get the output of ic regardless of the state of ic.enabled? 
Alternatively, do you have any tips that can be useful in similar situations?

**Comment by salabim** [comment]
I recommend having a look at 'peek', an alternative to icecream. Originally a fork of icecream, it is a much more feature ]-rich and more Pythonic debug print (and benchmark) tool.
In your case, you could do

import peek
peek.enabled = False
...
peek("regardless of enabled", enabled=True)

or

import peek
peek.enabled = False
peek_always = peek.new()
...
peek_always("regardless of peek.enabled")

Just have a look at 
www.salabim.org/peek

**Comment by yutaka-uno-nec** [comment]
Peek-python works well for me, except no color change option.
Anyway, thank you for your comment!
