### ISSUE TITLE
prettyprint dictionaries

### ISSUE THREAD

**Issue by shacker** [gruns/icecream#20]
Suggestion: I think a nice addition would be to prettyprint dictionaries, either by default or by configuration, since debugging often means staring into dict contents for clues. 

This could take up a lot of screen real estate for big/deep dicts, but I would still probably vote to enable it by default.

**Comment by gruns** [comment]
Wonderful suggestion.

Luckily, icecream has prettyprinted values since version v1.2. E.g.

```python
from icecream import ic

d = {1: 'asdf', 2: 'hihi', 3: {1: ic, 2: 2222, 3: {1: 'deeeeeeeeeep'}}}
ic(d)
```

prints

```python
ic| d: {1: 'asdf',
        2: 'hihi',
        3: {1: <icecream.icecream.IceCreamDebugger object at 0x7f297341d710>,
            2: 2222,
            3: {1: 'deeeeeeeeeep'}}}
```

Which version of icecream are you using?

**Comment by shacker** [comment]
Yikes, sorry about that. A very old version, clearly. Thanks for the great tool!

**Comment by gruns** [comment]
No sweat.

Thanks again, Scot. Don't hesitate to let me know if there's anything else I can do for you.

**Comment by dufferzafar** [comment]
@gruns Does this also work for OrderedDicts?

**Comment by gruns** [comment]
@dufferzafar just test it yourself :) 

```python
from icecream import ic
from collections import OrderedDict

od = OrderedDict()
od[1] = 'one'
od[2] = ['two', 'two']
od[3] = {3: 'three', 4: [4] * 4}

ic(od)
```

outputs

```python
ic| od: OrderedDict([(1, 'one'),
                     (2, ['two', 'two']),
                     (3, {3: 'three', 4: [4, 4, 4, 4]})])
```
