### ISSUE TITLE
Tests log on stderr

### ISSUE THREAD

**Issue by inakimalerba** [gruns/icecream#21]
Hi there!

While running the unittests, I realized that the output goes through stderr. Is there a reason for it?

```bash
 ±- python3 -m unittest tests/test_icecream.py > /dev/null 

......................
----------------------------------------------------------------------
Ran 22 tests in 0.071s

OK
```

I've spent some time trying to understand if its a side effect of the `captureStandardStreams` method, but couln't find the reason.

This matters because autopkgtest checks that the stderr is null :disappointed: 
https://salsa.debian.org/debian/python-icecream/-/jobs/17084

**Comment by gruns** [comment]
@inakimalerba Were you able to resolve this issue?

**Comment by inakimalerba** [comment]
Took me some time to realize its unittest's behaviour. :sweat_smile:  Sorry for the noise.
You can take a look at the packaging and tests on salsa.debian.org/debian/python-icecream 

I'll make a release soon. Any doubt just write me :)

**Comment by gruns** [comment]
Great!

Thank you again, @inakimalerba . Don't hesitate to let me know if there's anything
else I can do for you.
