### ISSUE TITLE
irondb

### ISSUE THREAD

**Issue by slavaGanzin** [gruns/icecream#25]
Hello I don't know how to reach you elsewhere, so I created issue here.

As I understand this guys https://www.irondb.io/ have conflict over your naming.

Why the heck github suspended irondb repo? 
Why you don't just rename it? I know it's "your name" too, but seriously what's the point? 

p.s. I just want to start use it, after you cut lodash :)

**Comment by gruns** [comment]
> Why the heck github suspended irondb repo?

IronDB was, tragically, taken offline temporarily due to a trademark notice in
the United States, where GitHub, now Microsoft, is located.

A requisite rename is forthcoming.

Thank you for creating this Issue, Slava. Don't hesitate to let me know if
there's anything else I can do for you.
