### ISSUE TITLE
Call icecream without having to import it each time.

### ISSUE THREAD

**Issue by feluxe** [gruns/icecream#29]
Hi there,

I like icecream a lot. :) ... However, I often fall back to `print()` because I'm to lazy to type in `from icecream import ic` before each call. I guess it would be awesome if one could add icecream to the builtins or globals or something.

I tried adding `ic()` to the buildins like this: 

```python
import builtins

def ic(x=None):
    from icecream import ic as ic_tmp
    if x:
        ic_tmp(x)
    else:
        ic_tmp()


builtins.ic = ic

```

This allow me to call `ic()` without having to import it first, but of cause this messes up `ic`'s output...

I was wondering if anyone has got an idea how to make `ic` global or builtin without breaking it?

**Comment by gruns** [comment]
I know. I wish `ic()` was included in Python, too. One day.

Until that fateful day, two ideas spring to mind:

1. Add `from icecream import ic` to your interpreter's `site.py` file,
   e.g. `/usr/lib/python3.6/site.py`. `site.py` is automatically imported during
   initialization. See

     * https://docs.python.org/3/library/site.html

   This is bad practice in production, but perhaps acceptable to you for local
   development.

2. Import `ic()` at the top of every file with

```python
try:
    from icecream import ic
except ImportError:  # Graceful fallback if IceCream isn't installed.
    ic = lambda *a: None if not a else (a[0] if len(a) == 1 else a)  # noqa
```

This import fails gracefully if icecream isn't installed.


Do either of these techniques suffice for your needs?

**Comment by feluxe** [comment]
Thanks for your reply!

> I know. I wish ic() was included in Python, too. One day.

Totally! I heavily rely on print-debugging, an `ic()` builtin would be a *gigantic* improvement.

I tried `1)` within a virtualenv (via `pipenv`) but, I couldn't get it to work.

`2)` is too much boilerplate.

Hmm, maybe I'll go for a keyboard shortcut that automatically pastes:

```python
from icecreame import ic
ic()
```

**Comment by gruns** [comment]
> I tried 1) within a virtualenv (via pipenv) but, I couldn't get it to work.

What did you try, exactly?

**Comment by feluxe** [comment]
> What did you try, exactly? What steps did you take?

In a venv I ran `pipenv --venv`. That gives me the path to the interpreter:
```
/home/peter/.local/share/virtualenvs/myproject-gWbaV4B9
```

Like you said, there is a file `site.py` in:

```
/home/peter/.local/share/virtualenvs/myproject-gWbaV4B9/lib/python3.7/site.py
```

I added `from icecream import ic` to the end of the file, just before the line that sais `if __name__ == "__main__":`.

I have put `ic()` into `foo.py` and ran `pipenv run python foo.py` and get:

```
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    ic("nice")
NameError: name 'ic' is not defined
```

**Comment by gruns** [comment]
I dug more. Indeed adding

```python
from icecream import ic
```

to `site.py` fails. But modifying the global `__builtins__` dictionary in
`sete.py` works. Ish.

In `site.py` add

```python
from icecream import ic
__builtins__['ic'] = ic
```

and run

```
ic('test')
```

`ic()` fails.

```
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?
```

IceCream gets confused. Perhaps `inspect` returns strange values when imported
in a different module than its execution file. I'll dig further shortly.

**Comment by rec** [comment]
IMHO, the keyboard macro is by far the best solution.  Anything that "automatically" adds some symbol to any .py file is just a terrible risk, and not something you can export to others either.  

One day you're going to forget and check in a naked `ic` and there will be tears and wailing.  :-)

**Comment by feluxe** [comment]
@rec I agree. I have a keyboard macro on `iccc` now and it feels alright.

In the long run we should make some noise for `icecream` and hope it finds its way into the default `builtins` of Python and other languages. :)

**Comment by merwok** [comment]
The sitecustomize and usercustomize modules are meant for this kind of thing, please don’t recommend editing site!

Alternatively, you could check how [q](https://github.com/zestyping/q) does its auto-import magic and copy that.

**Comment by alexmojaki** [comment]
> But ic() fails.

Looks like it works if you also check `callFrame.f_builtins` inside `determinePossibleIcNames`.

> One day you're going to forget and check in a naked ic and there will be tears and wailing. :-)

You could mitigate that risk with code like this:

```python
def ic(*args):
    if not args:  # E.g. ic().
        passthrough = None
    elif len(args) == 1:  # E.g. ic(1).
        passthrough = args[0]
    else:  # E.g. ic(1, 2, 3).
        passthrough = args

    return passthrough


if DEBUG:  # or whatever check for non-production
    try:
        from icecream import ic
    except ImportError:
        pass

__builtins__['ic'] = ic
```

> Alternatively, you could check how q does its auto-import magic and copy that.

I may be wrong but I don't think `q` auto-imports. I think it just makes the module callable so you can do `import q; q()`. Which is useful too and may be good for icecream, though more so if the package name was just `ic`.

**Comment by gruns** [comment]
> Which is useful too and may be good for icecream, though more so if the
> package name was just ic.

I wanted to do this, but unfortunately all good double letter, and single
letter, package names have been taken.

Insofar, it's not worth making a three letter macro, like `icu()`. Two letters
is short and sweet.

Plus `ic(X)` is cute, as it reads like `I see X`.

**Comment by alexmojaki** [comment]
This is already implemented by `install()`, right?

**Comment by gruns** [comment]
> This is already implemented by install(), right?

yep! great eyes @alexmojaki :eyes: 

closing this issue
