### ISSUE TITLE
Compatibility with ipython "autoreload" extension

### ISSUE THREAD

**Issue by lukelbd** [gruns/icecream#42]
Currently, icecream breaks if you try to use it inside a module "reloaded" with the [`%autoreload` ipython extension](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html). For example, with the file `tmp.py` containing the lines:

```python
# tmp.py
from icecream import ic
a = 1
ic(a)
```

If I start an ipython session I get the following:

```python
In [1]: %load_ext autoreload
In [2]: %autoreload 2
In [3]: import tmp
ic| a: 1
```

Then *certain* changes break icecream. For example changing the file contents to

```python
# tmp.py
from icecream import ic
a = 2
ic(a)
```
works just fine:

```python
In [4]: import tmp
ic| a: 2
```

However doing more complicated things, for example adding an import statement, breaks it:

```python
# tmp.py
import os
from icecream import ic
a = 1
ic(a)
```

results in the following:

```python
In [5]: import tmp
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an inte
rpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the unde
rlying source code change during execution?
```

I don't have a comprehensive list but, more often than not, `icecream` seems to fail when I have interactive dependencies or am working with functions/classes.

Would it be possible to fix this?

**Comment by alexmojaki** [comment]
Haven't tested this yet but I can make a good guess what the problem is. `executing` (which icecream uses) has a cache from filenames to file contents. When you autoreload, executing still remembers the old file contents. Seeing a mismatch between its version of the source code and the compiled bytecode, it doesn't try to identify the call node.

Given that cache invalidation is one of the two hard problems in computer science, I will need some time to think about a solution.

**Comment by gruns** [comment]
Cache invalidation indeed :).

Even with simple cache invalidation via a file's last modified date, my
gut says that will work (hopefully) will work 90% of the time.

Of course, fundamentally, there's no way to gaurantee access to the
source of a file *exactly* as executed at the time of `ic()` execution
in Python.

Imagine a torturous scenario where the `.py` file that calls `ic()` is
modified/mangled repeatedly every few ms. In such a case, by the time
`ic()` has run and read the source file, it's changed umpteen times and
`ic()` can't determine what the source looked like at the time `ic()`
was executed. Not without a microsecond-precise time machine, that is.

Luckily, that scenario is uncommon. I bet in the 90% use case, simply
reloading and reparsing the source file if we detect a change in the
last modified date suffices and things work as expected.

**Comment by lukelbd** [comment]
The underlying source file is not changing very often. I work on python software projects by (manually) making changes to my module code, relying on `%autoreload` to refresh those changes, and testing those changes in an ipython session.

No daemons here; I just add `ic()` calls inside my module code for print-debugging, but it often causes the above error. The source file is not changing repeatedly during one run.

I found some telling examples in addition to that import statement-example. Consider the simple module:

```python
# foo.py
from icecream import ic

def foo():
    x = 'foo'
    return x
```

If I add an *initial* `ic()` invocation everything is fine:

```python
def foo():
    x = 'foo'
    ic(x)
    return x
```

```python
In [7]: foo.foo()
ic| x: 'foo'
Out[7]: 'foo'
```

Then if I change variables or the code around the `ic()` invocation, everything is still fine:

```python
def foo():
    x = 'bar'
    ic(x)
    return x
```

```python
In [8]: foo.foo()
ic| x: 'bar'
Out[8]: 'bar'
```

*However* if I change what I'm passing to `ic()` `autoreload` seems to consistently break it:

```python
def foo():
    x = 'bar'
    ic(x, 'test')
    return x
```

```python
In [13]: foo.foo()
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?
Out[13]: 'bar'
```

If I revert *back* to the original invocation within the *same ipython session*, everything is fine again:

```python
def foo():
    x = 'bar'
    ic(x)
    return x
```

```python
In [14]: foo.foo()
ic| x: 'bar'
Out[14]: 'bar'
```

Also, it is still broken if I try to delete the `ic` invocation, autoreload the module, add a new `ic` invocation, and autoreload the module again.

**Comment by alexmojaki** [comment]
> If I add an initial ic() invocation everything is fine:

Because the cache is loaded for the first time.

> Then if I change variables or the code around the ic() invocation, everything is still fine:

Changing the values of some constants is such a small change that `executing` doesn't notice the difference. It's a very special case.

> However if I change what I'm passing to ic() autoreload seems to consistently break it:

But any change to the actual structure of the code, such as adding an import, or really almost any change, will break things.

> If I revert back to the original invocation within the same ipython session, everything is fine again:

A bit like a broken clock that's right twice a day, the cache now contains the right thing again.

> Also, it is still broken if I try to delete the ic invocation, autoreload the module, add a new ic invocation, and autoreload the module again.

Yes, that doesn't clear the cache.

This is all expected, and I will get to this because it matters to me beyond icecream, but I haven't had time yet.

**Comment by alexmojaki** [comment]
OK, `pip install -U executing` (not icecream - executing) and try again.

**Comment by lukelbd** [comment]
Awesome, [executing v0.5.0](https://github.com/alexmojaki/executing/releases/tag/v0.5.0) fixed it! Thanks for the quick action! Can't reproduce the bug anymore so I think this issue can be closed.

**Comment by gruns** [comment]
@alexmojaki Awesome work. :+1:

Shall we mint a new version of icecream with `executing >= 0.5.0`?

**Comment by alexmojaki** [comment]
Nah, keep the version loose.
