### ISSUE TITLE
lua part of icecream

### ISSUE THREAD

**Issue by wlingze** [gruns/icecream#47]
hei! I have finished the lua version of icecream, see if it is qualified.
[icecream-lua](https://github.com/wlingze/icecream-lua),

**Comment by alexmojaki** [comment]
Can you make a PR similar to https://github.com/gruns/icecream/pull/72 ?

**Comment by wlingze** [comment]
ok, it has been [submitted](https://github.com/gruns/icecream/pull/75) now!
