### ISSUE TITLE
ic | Error when using ic with hydra

### ISSUE THREAD

**Issue by khuyentran1401** [gruns/icecream#49]
## Description
Hi Ansgar, when trying to use ic inside a function that uses [hydra](https://hydra.cc/), a Python library for configuration, I got this error:

```bash
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?
```
## How to replicate
```python
from icecream import ic 
import hydra

@hydra.main(config_path="../configs", config_name="strategies")
def main(cfg):
    
    ic(2)

if __name__=='__main__':
    main()
```
I say icecream is not compatible with hydra because when removing the decorator hydra, everything works again.

I wonder if you know what could cause this error? Since hydra is a framework that I use frequently, knowing how to fix this error will be really helpful for me. Thank you!

**Comment by alexmojaki** [comment]
I don't know how to use hydra, can you give the full file layout that makes this script runnable?

**Comment by oracle3001** [comment]
I encounter the same issue with using PyCharm when running in debug.

**Comment by alexmojaki** [comment]
@oracle3001 do you mean you get this error?

> `ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?`

That message is completely generic and can happen for many reasons. If you're not using hydra, please open another issue and give more details.

**Comment by khuyentran1401** [comment]
I was trying to recreate the same error using another script that uses hydra but I cannot. It might be because of some other problems. I will close this for now and will open it when I detect the cause of this error.
