### ISSUE TITLE
Make a command line option for icecream module to find and delete all the `ic` statements in the code

### ISSUE THREAD

**Issue by AthulMuralidhar** [gruns/icecream#50]
# Description

- This is a great tool for debugging python code. If we could just add a CLI with a `remove` keyword like so:
```bash
ic remove all
```
this would save devs a lot of time a la `Black` the linter! 
- Some pseudo code (for the implementation of the CLI functionality):
```python
from os import listdir
from os.path import isfile, join
import re

onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

for file_name in onlyfiles:
    with open(file_name, w):
          re.search("ic").seek(). --> or something like this
          # find and replace logic here
```

**Comment by alexmojaki** [comment]
Using the AST instead of regex:

```python
import ast
from executing import Source
import asttokens.util

filename = "..."

source = Source.for_filename(filename)
atok = source.asttokens()

replacements = []
for node in ast.walk(source.tree):
    if isinstance(node, ast.Call) and getattr(node.func, "id", "") == "ic":
        if isinstance(node.parent, ast.Expr):
            start, end = atok.get_text_range(node)
            end += 1
        else:
            start, end = atok.get_text_range(node.func)

        replacements.append((start, end, ""))

print(asttokens.util.replace(source.text, replacements))
```

Converts:

```python
from icecream import ic

ic(1)
ic(1, 2)
x = ic(3)
y = ic(4, 5)
```

into:

```python
from icecream import ic

x = (3)
y = (4, 5)
```

But really, if your icecream use is this heavy, consider using https://github.com/alexmojaki/snoop or https://github.com/alexmojaki/birdseye so you can see all values with less code modification.

**Comment by gruns** [comment]
@AthulMuralidhar if you just want to disable `ic()` output, you can call `ic.disable()`

this does not, of course, remove `ic()` from your code. but makes each `ic()` call a no -op

**Comment by AthulMuralidhar** [comment]
Guys, I am not sure if you understand me correctly - From this page: https://github.com/gruns/icecream -  the code snippet:
```python
from icecream import ic

def foo(i):
    return i + 333

ic(foo(123))
```
what I would like is this -  after i've done by debugging i do something like this: `python -m icecream test.py remove all` and `test.py` has the icream import and usage (as defined above). Now the `test,py` should look something like this:

```python

def foo(i):
    return i + 333
```

I hope this is clear -  sorry for the cryptic desc haha. Let me know your thoughts @alexmojaki @gruns

**Comment by alexmojaki** [comment]
You were perfectly clear the first time, and both of our comments were relevant.

I gave a partial implementation of that script, specifically removing ic() calls in a robust way. Removing imports is just not something I bothered to implement.

Both of us gave you general tips on the broader problem of how to make the process of debugging smoother and more efficient, in which removing ic() from your code is not even a requirement.

Your proposal is a fair amount of work to implement and maintain, so it's important to talk about how useful and important this feature is relative to alternative ways to accomplish similar goals.

**Comment by AthulMuralidhar** [comment]
thanks for the reply @alexmojaki :) It maybe wasn't clear to me haha. But anyway - thanks for the lib and keep up the good work!

**Comment by alexmojaki** [comment]
I think the best thing would be to make a separate project which does this kind of thing more generically, not just for icecream. It could look for and remove:

- ic()
- breakpoint()
- pdb.set_trace()
- print()
- log.debug()
- 1/0
- assert 0
- Calls to other debugging libraries, such as snoop, pysnooper, birdseye, q, etc.

I imagine many users would find that useful and interesting even if they've never heard of icecream.

The icecream README could easily have a section saying `pip install undebug; python -m undebug ic`.

Or maybe it could be a plugin for black, I don't know how that stuff works.

This might exist already. I couldn't find anything like it at a glance but you should do a thorough search.

**Comment by gruns** [comment]
as usual, I agree with @alexmojaki :)

a general purpose tool to cleanly excise function invocations, eg `ic()`, would be more broadly useful than just for icecream

if/once such a tool exists, we could see how best to integrate it into icecream to solve your use case

> Btw - are you guys planing on implementing this functionality? Shall i make a pr for this?

either way, let's back up

why, exactly, do you want to rip out of all the `ic()` invocations over just calling `ic.disable()`? eg

1) cleaner non-debug code?

2) "performance"? (have you benchmarked it?)

3) reduce import footprint?

broadly speaking, even production code typically runs with logging enabled in some capacity. one potentially 'better' avenue could be to more tightly integrate icecream with other logging tools, such that in 'production' icecream's output changes to include more details and writes to logs instead of stderr

this would indeed be scope creep; icecream is intended for development and debugging. not logging. but if relevant to you, worth having the conversation regardless

**Comment by AthulMuralidhar** [comment]
my main motivation for the feature request was making the debugged code production ready. It is clear that it is maybe not be a priority for this project.  Thanks for the inputs! Please close this issue :)  And again, keep up the good work :D

**Comment by gruns** [comment]
does your production code have other, non-`ic()` logging?

if so, is the output of `ic()` as you're using it useful wrt logging? that is, once your code is in 'production' (whatever that means for you), do you care about the output of the `ic()` calls you used during development?

Im closing this issue but would like to continue the discussion to better understand your use case

**Comment by AthulMuralidhar** [comment]
>does your production code have other, non-ic() logging?

yes - we mainly use this: https://docs.python.org/3/library/logging.html that comes shipped with python. And `ic` was just a try out. We use it internally for debugging purposes only - not logging. The tagline if i understand correctly, was to stop using print statements during debugging, that is the use-case for us exactly.

>if so, is the output of ic() as you're using it useful wrt logging?

No. Not as far as our current implementation goes. We usually remove all the `ic` calls by hand. This is again the main motivation for the CLI
