### ISSUE TITLE
Cannot import install

### ISSUE THREAD

**Issue by mosesontheweb** [gruns/icecream#51]
Hi,

just installed `icecream` on a sample project and tried to use it according the instructions by importing `install` and use it as a builtin module. For some reason `install` isn't there:
```
ImportError: cannot import name 'install' from 'icecream'
```
Either it has been removed and the docs on the Github page are old or I missed something.
Regards, Thomas

**Comment by FlorianWilhelm** [comment]
I got exactly the same problem with version 2.0.

**Comment by mrchaosbude** [comment]
You have to do '**pip install icecream**'  in your console
And then in your project '**from icecream import ic**'

**Comment by gufipy** [comment]
The Import Trick  as explained in the readme doesn't work.
 
from icecream import install

install() adds ic() to the builtins module, which is shared amongst all files imported by the interpreter. Similarly, ic() can later be uninstall()ed, too.

same problem with version 2.0

**Comment by gufipy** [comment]
as written in 
https://github.com/gruns/icecream/issues/48#issue-769396916
it is a problem of two different version 2.0.0 installed with 

pip install icecream

and 

# files from github
python setup.py install

**Comment by FlorianWilhelm** [comment]
Okay, thanks @gufipy for clarifying this. So all we need to do is waiting for another release.

**Comment by gufipy** [comment]
You could use the github version of ice cream. I deinstalled the pip- and
use now the github version of icecream. And install() works perfect


Florian Wilhelm <notifications@github.com> schrieb am Fr., 22. Jan. 2021,
07:19:

**Comment by gruns** [comment]
I just deployed icecream v2.1.0, which includes `install()` and `uninstall()`

upgrade with `pip install icecream --upgrade`

thank you, everyone, for creating this issue and for using icecream! :heart:
