### ISSUE TITLE
issue when using icecream on Windows PyCharm Debugger "Evaluate tool"

### ISSUE THREAD

**Issue by BarRozenman** [gruns/icecream#61]
I've installed icecream and it seems to work great but when I try to use  the "Evaluate tool" on the PyCharm Debugger 
as shown in the picture it's printed this message:
 
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?

which I could not find a solution on the web

![tempsnip](https://user-images.githubusercontent.com/45449223/110455695-6a9b1280-80d1-11eb-8e80-4e66d68315e9.png)

**Comment by alexmojaki** [comment]
Indeed, the source code is not available in this situation.

Besides, there's no point in using ic() here, you can see the code right there.
