### ISSUE TITLE
Using `ic` in Jupyter Notebook outputs extra variable

### ISSUE THREAD

**Issue by NMZ0429** [gruns/icecream#62]
Thanks in advance for this wonderful package.

This is not really issue but wondering if I can get rid of it.
When I am using `ic` in Jupyter Notebook it always output the content twice if `ic` is called at the end of the cell. For example, the code cell 

```python
from icecream import ic 

x = 5
ic(x)
```
outputs
```
ic| x: 5
5
```

As another example,
```python
ic(5)
ic(10)
```
outputs
```
ic| 5
ic| 10
10
```

This does not happen if `ic` is no the end of the cell.

**Comment by gruns** [comment]
this is likely because `ic()` returns the value you pass it so you can embed it in existing logic, eg `foo(ic(3))` still calls `foo()` with `3`

test this: instead of 

```python
from icecream import ic 

x = 5
ic(x)
```

try

```python
from icecream import ic 

x = 5
_ = ic(x)
```

is `5` still output?

**Comment by alexmojaki** [comment]
The point of the feature in the notebook is that you can just put `x` at the end of the cell to see what `x` is. Just like you can evaluate expressions in the shell without having to print them.

**Comment by NMZ0429** [comment]
@gruns @alexmojaki 

That was exactly what's happening but its's a nice feature! Thank you guys so much :)

**Comment by maciejkos** [comment]
Firstly, thanks for this package! I discovered it a few days ago and really like it!

@alexmojaki I see the benefit of this feature, but personally would rather disable it. Could you please tell me if it is possible? I work with long dictionaries and printing them twice makes working with notebooks a little less pleasant. 

Thanks!

**Comment by gruns** [comment]
if this confuses enough users - which it appears to, especially in notebooks - we can definitely add a flag to disable it

**Comment by alexmojaki** [comment]
Let me clarify further. If you have code like this:

```python
from icecream import ic 

x = {...}
ic(x)
```

Change it to:

```python
x = {...}
x
```

That's it. `x` will be printed just by putting it at the end.

That's the feature I was referring to. It's a feature of Jupyter/IPython, not icecream. In this situation there is no need to use icecream at all, at least not for the very last line in the cell.

**Comment by maciejkos** [comment]
Thanks for such a prompt reply, @alexmojaki! 

I must have confused something; my apologies. 

I am looking for a solution to the following problem.

This code:
```
import string
from icecream import ic

my_dict = {}
for letter in string.ascii_letters[:10]:
    my_dict[letter] = 1

ic(my_dict)
```
outputs:
```
ic| my_dict: {'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 1, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1}
{'a': 1,
 'b': 1,
 'c': 1,
 'd': 1,
 'e': 1,
 'f': 1,
 'g': 1,
 'h': 1,
 'i': 1,
 'j': 1}
```

Is it possible to have ic only output the below?
`ic| my_dict: {'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 1, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1}`

**Comment by alexmojaki** [comment]
Ah, so the problem is IPython's pretty printing. Here's 3 options:

```python
_ = ic(my_dict)  # as suggested by gruns

ic(my_dict)
None

print(my_dict)
```

Point is, if the last line is an expression with a non-None value, it gets printed.

You can disable pretty printing entirely in IPython with the magic command `%pprint`: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pprint
