### ISSUE TITLE
Enable installing icecream with conda

### ISSUE THREAD

**Issue by tshtatland** [gruns/icecream#63]
Could you please enable installing `icecream` using `conda`?

**Comment by gruns** [comment]
ive never used conda and im not familiar with it

what's necessary to make icecream compatible with conda?

PR welcome!

**Comment by alexmojaki** [comment]
You have to add a recipe to conda-forge, see https://conda-forge.org/#add_recipe . It's a whole process that's reviewed by humans. I've done it for some of my packages (including executing, fortunately!) and it's not terrible but I don't want to do it again.

**Comment by alexmojaki** [comment]
Recipe proposed here: https://github.com/conda-forge/staged-recipes/pull/14460

**Comment by alexmojaki** [comment]
Published! https://anaconda.org/conda-forge/icecream

Someone let me know if it works

**Comment by tshtatland** [comment]
Does not work for me:
```
% conda search icecream       
Loading channels: done
No match found for: icecream. Search: *icecream*

PackagesNotFoundError: The following packages are not available from current channels:

  - icecream

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


% conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by alexmojaki** [comment]
I'm guessing it just needed time, how about now?

**Comment by tshtatland** [comment]
Works OK, thank you!

**Comment by scheung38** [comment]
conda install -c conda-forge icecream

But in debug mode:

from icecream import ic

region_set = set(df['Region'].unique().tolist())
ic(region_set) <---- ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?

**Comment by gruns** [comment]
@scheung38 how are you running the python program? and might the source code actually have changed underneath icecream?
