### ISSUE TITLE
Jupyter Stderr

### ISSUE THREAD

**Issue by Mathemmagician** [gruns/icecream#77]
Since ic outputs to stderr, it displays weirdly in Jupyter, especially when the cell is both printing and ic-ing a lot of stuff at the same time, I've observed the order of output to be inconsistent at times. Would be nice to be able to redirect to stdout instead.

Maybe something like:
```
from icecream import ic
ic.configureOutput(stdout=True)
```

---

After digging deeper, I found out that what I'm looking for can be accomplished with:
```
ic.configureOutput(outputFunction=print)
```
It took me a while to figure it out, so I'm sure there are others. Should probably be added to the README as an example showing to how to redirect to stdout instead of stderr. Although, the line above is quite long, something shorter would be nicer.

P.S. Jupyter inconsistency can be achieved with:
```
from icecream import ic
for i in range(1, 100):
    print(i)
    ic('test')
```
outputs with messed up order:

<img width="779" alt="Screen Shot 2021-04-16 at 10 49 03 PM" src="https://user-images.githubusercontent.com/42552279/115099746-f2acdd00-9f05-11eb-87a9-d3dabf081255.png">

Adding `flush=True` solves it, but obviously rather just have everything in stdout instead.

**Comment by gruns** [comment]
is `flush=True` not required for stdout, only for stderr?

**Comment by Mathemmagician** [comment]
That's right, only stderr. 

This makes sense since `ic.configureOutput(outputFunction=print)` sends both inputs to the same stream, so the order is preserved.

**Comment by gruns** [comment]
> This makes sense since ic.configureOutput(outputFunction=print) sends both outputs (normal print and ic) to the same stream, so the order is preserved.

aha

> Should probably be added to the README as an example showing to how to redirect to stdout instead of stderr.

youre actually the first one to express a desire here. when others express the same, ill add it to the readme

or ill include this as an example in the forthcoming overhaul to icecream's output. see https://github.com/gruns/icecream/issues/31

does `ic.configureOutput(outputFunction=print)` resolve this for you for now? if so, ill close this issue

**Comment by Mathemmagician** [comment]
Surprised I'm the first one! I would imagine most data scientists who work with Jupyter would run into this, but maybe I'm wrong.

`ic.configureOutput(outputFunction=print)` worked, yes.

**Comment by gruns** [comment]
> Surprised I'm the first one! I would imagine most data scientists who work with Jupyter would run into this, but maybe I'm wrong.

future issue reader: if you want a way to print to stdout highlighted, like in the readme, please let us know!

thank you, @Mathemmagician! :open_hands:

**Comment by jerabaul29** [comment]
Had the same issue with the Xonsh shell, this fixed it, thanks :) .

**Comment by gruns** [comment]
> ic.configureOutput(outputFunction=print) worked, yes.

this means the issue lies in writing to stderr, not (afaict) in the underlying icecream library itself

@jerabaul29 what behavior do you observe, exactly, with icecream outputting to stderr in xonsh? was it slow? did output stutter? if possible, can you take a video and share it here so i can see what you see?

perhaps the best path for icecream is to try to detect (how?) when icecream runs in an environment where stderr has issues. then, in such an environment, output to stdout instead of stderr

**Comment by jerabaul29** [comment]
Sorry for the late reply. As said, using ```ic.configureOutput(outputFunction=print)``` as suggested in this thread solved the problem, so nothing special more from my side. The issue was being output order being messed up.

**Comment by gjvnq** [comment]
Hey, while this technically solves the issue, it would be nice to have colorful printing on Jupyter by default.

**Comment by gjvnq** [comment]
I found a work around for the coloring problem that plays nice with Jupyer Lab. I simply added the following to the top of my notebook:

```py
try:
    from icecream import ic, colorize as ic_colorize
    ic.configureOutput(outputFunction=lambda s: print(ic_colorize(s)))
    ic('Hey, icecream is installed and working.')
except ImportError:  # Graceful fallback if IceCream isn't installed.
    ic = print
    ic('Using work around as icecream is not installed.')
```

I suggest you either add this to the documentation or even better autodetcte if the script is running on Jupyter and auto change to stdout.

Aparently this function works: (got from https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook )

```py
def isnotebook():
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            return True   # Jupyter notebook or qtconsole
        elif shell == 'TerminalInteractiveShell':
            return False  # Terminal running IPython
        else:
            return False  # Other type (?)
    except NameError:
        return False      # Probably standard Python interpreter
```

**Comment by danieldjewell** [comment]
I'm not sure that this is 100% the proper way to interface with the Jupyter/IPython API? 

I was trying out `icecream` in the IPython REPL (from the command line) and was running into double output issues ... One solution that seemed to help was: 

```python3

import IPython
ic.configureOutput(outputFunction = IPython.lib.pretty.RawText) 
``` 

This did break colorizing the output ... I suspect that interfacing directly with the IPython API is the "right" way to ensure that output works both in the IPython console REPL and also in Jupyter notebooks ...  https://ipython.readthedocs.io/en/stable/api/generated/IPython.lib.pretty.html
