### ISSUE TITLE
Add this lib to the wiki at PythonDebuggingTools

### ISSUE THREAD

**Issue by patkujawa-wf** [gruns/icecream#8]
This seems like a handy tool that folks should be able to find via https://wiki.python.org/moin/PythonDebuggingTools. I don't have edit access to that wiki, but I've requested it.

**Comment by patkujawa-wf** [comment]
Well, I got permissions, but now their server is not responding. I was going to add this blurb:

> "Sweet and creamy print debugging" - a nice alternative to using print statements to debug values and locations in the stack.

**Comment by gruns** [comment]
Awesome.

> I was going to add this blurb:
>
>> "Sweet and creamy print debugging" - a nice alternative to using print
>> statements to debug values and locations in the stack.

I would use this blurb/description (the Notes column):

```
Sweet and creamy print debugging -- easily inspect variables, expressions, and
code execution with a single, simple function call.
```

It's a wiki after all, too, so the blub/description can always be tweaked and
improved later.

Don't hesitate to let me know how else I can help.

**Comment by gruns** [comment]
@patkujawa-wf IceCream still hasn't been added to the wiki yet.

What can I help with?

**Comment by patkujawa-wf** [comment]
Thanks for the reminder. The server is responding better today :)
![image](https://user-images.githubusercontent.com/6391742/36927421-c47a14ec-1e3a-11e8-8e24-dc05a7ea115b.png)

**Comment by gruns** [comment]
Wonderful!

Thank you, again, @patkujawa-wf. Don't hesitate to let me know if there's anything I can do for you.
