### ISSUE TITLE
How to ic(something) with only linenumber as an extra information?

### ISSUE THREAD

**Issue by noisnemid** [gruns/icecream#81]
I don't need that much information of the following config

```
ic.configureOutput(includeContext=True)
```
this will mess the console information mess up.

I only need the line number information and the variable value.

How to config it?

such as
```
includeLinenumber=True
```
?

**Comment by alexmojaki** [comment]
Maybe `prefix` should accept a format string, so you can write `ic.configureOutput(prefix="ic | {lineno} | ")` or something.

You can try https://github.com/alexmojaki/snoop :

```python
import snoop

snoop.install(columns=[lambda event: event.line_no])
snoop.pp(1 + 2)
```

**Comment by noisnemid** [comment]
> Maybe `prefix` should accept a format string, so you can write `ic.configureOutput(prefix="ic | {lineno} | ")` or something.
> 
> You can try https://github.com/alexmojaki/snoop :
> 
> ```python
> import snoop
> 
> snoop.install(columns=[lambda event: event.line_no])
> snoop.pp(1 + 2)
> ```

Thanks for your answer.
the prefix does  recognize the {lineno} arg, and the snoop is very nice!

and here I got a quick code to do the things:

```
import sys
icc = lambda x : print(f'{sys._getframe().f_lineno}:{x}')
icc('anything...')
```

**Comment by alexmojaki** [comment]
> the prefix does not recognize the {lineno} arg

It wouldn't, I was suggesting a feature that could be added to solve your problem.

> `icc = lambda x : print(f'{sys._getframe().f_lineno}:{x}')`

That's showing the line where the lambda is defined, not where `icc` is called. Try `sys._getframe(1)`. But of course this also won't show the expression which is the point of ic(), it'll only show the value.

**Comment by noisnemid** [comment]
> > the prefix does not recognize the {lineno} arg
> 
> It wouldn't, I was suggesting a feature that could be added to solve your problem.
> 
> > `icc = lambda x : print(f'{sys._getframe().f_lineno}:{x}')`
> 
> That's showing the line where the lambda is defined, not where `icc` is called. Try `sys._getframe(1)`. But of course this also won't show the expression which is the point of ic(), it'll only show the value.

ok. it seems only snoop is the right thing to fit the demand here.

**Comment by gruns** [comment]
> Maybe prefix should accept a format string, so you can write ic.configureOutput(prefix="ic | {lineno} | ") or something.

:+1: for me there

though @noisnemid: how much of an inconvenience is it that the filename's inclusion? does this extra output line width screw up your formatting somehow? or are you just working with a small set of files and thus you don't care about the filename's inclusion?

**Comment by noisnemid** [comment]
> > Maybe prefix should accept a format string, so you can write ic.configureOutput(prefix="ic | {lineno} | ") or something.
> 
> +1 for me there
> 
> though @noisnemid: how much of an inconvenience is it that the filename's inclusion? does this extra output line width screw up your formatting somehow? or are you just working with a small set of files and thus you don't care about the filename's inclusion?

For complex python projects filename is of course a must, but in many cases esp. when testing a single module, or sometimes I run a single script with many outputs ant the outputs must be monitored, the things got a little complex when there are too much unnecessary information like 'filename' for it's too long while line-number is just a digit which make it less intrusive.

The key concept or convention is , as ic is a debugging tool, the output format will be much better if it's highly formattable, esp. like formating-string-styled args. The choice should be left to the user, and the tool gives the ability.

I noticed the source code of ic has 'linenumber'  inner parameter, but I don't know how to extract it out.

So it will be very nice if this feature-like suggestion could be accepted :)

Thanks for the amazing tool of ice cream!

**Comment by gruns** [comment]
> The key concept or convention is , as ic is a debugging tool, the output format will be much better if it's highly formattable

ya. no problem here beyond keeping things simple

if the filename + linenumber suffices 99% of the time, just do that and keep the library lean and mean

you're the first one to want context as line number only

**Comment by noisnemid** [comment]
```
import inspect
icc = lambda x: print(f'{inspect.getframeinfo(inspect.stack()[1][0]).lineno}: {x} ')

icc('something') # 4
icc('something') # 5
icc('something') # 6
```
