### ISSUE TITLE
multiple settings for ic ?

### ISSUE THREAD

**Issue by dcsan** [gruns/icecream#85]
If i setup the ic prefix I would like it to be local to that one file.
ie I want to have a different short prefix telling me where my logs are coming from, not globally (separate from code context, which is a bit too verbose).

but when I set a config it will override another place.

is there a way to create instances of ic or is it one global shared state?

**Comment by alexmojaki** [comment]
https://github.com/gruns/icecream/blob/e952dc5b36af4671867b052225863299e396d30c/icecream/icecream.py#L333

It's not global, making more instances should work.

**Comment by dcsan** [comment]
TIL! thanks
