### ISSUE TITLE
__version__.py not found in __init__.py

### ISSUE THREAD

**Issue by EdLipson5117** [gruns/icecream#87]
I'm using fbs to build Qt PySide2 programs. When I added icecream and test the programs using the 'run' option, everything is fine. If I 'freeze' the program into an exe, the program can't start as the __version__.py module is not found. pyinstaller is used to create the exe. it does not appear in the icecream folder. I've used the fbs/pyinstaller suggested hidden_imports=['icecream.__version__']. That copies the module as a .pyc to the proper location. The open still fails.

  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\edlip\appdata\local\programs\python\py91\lib\site-packages\icecream\__init__.py", line 20, in <module>
    with open(pjoin(dirname(__file__), '__version__.py')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\edlip\\Documents\\code\\vsc_ws\\fitbit_charge\\target\\Fitbit_Charge\\icecream\\__version__.py'
[16652] Failed to execute script main

I'm not sure how to best solve this. I can just stop using icecream (but I like the debugging output), I can swap in and out the module importing and installing (but I don't know how that will 'play' with git). I'm looking for suggestions on how to resolve this in a clean, pythonic manner.

**Comment by alexmojaki** [comment]
@gruns I don't get the logic behind the manual open and exec, why not just import? Seems like something you'd only need to do in setup.py.

**Comment by Arjun-Somvanshi** [comment]
I have been facing the same issue while building apps importing the icecream package both for windows and android, using the kivy library. I think a solution that might work is simply importing from the __version__.py file?

**Comment by gruns** [comment]
> I don't get the logic behind the manual open and exec, why not just import?

it was the same hack copied from setup.py to avoid enumerating all the metadata variables explicitly. ie to avoid having to maintain a list like this:

```
from .__version__ import __title__, __description__, __url__, __version__
from .__version__ import __author__, __license__, __copyright__
```

ill remove it

**Comment by gruns** [comment]
fixed in https://github.com/gruns/icecream/commit/c6d7e8f70f928d7309de7327bd9c223aab2571f8

thank you @EdLipson5117! 🙌
