### ISSUE TITLE
Ugly output 

### ISSUE THREAD

**Issue by hutner700** [gruns/icecream#89]
I don't know why, but the output is going to the next line: 

```py
from icecream import ic
from datetime import datetime
import time


def square(num):
    return num*num

def now():
    return f'[Debug | {datetime.now()}]'

#ic.disable()
#ic.enable()

ic.configureOutput(prefix=now(),includeContext=True)
b = 2
a = ic(square(b))
ic(f'Iniciando Y {b}')
time.sleep(10)

```
(its just a test file)
but the exit is that: 
![image](https://user-images.githubusercontent.com/65544215/122761274-7078c600-d272-11eb-9023-d9adc2648dd6.png)
what I can do to have all in one line like ->
```py
[ Icecream.py:16 in <module> | 2021-06-21 09:18:48.044729 ] square(b): 4
```

**Comment by alexmojaki** [comment]
Try `ic.lineWrapWidth = float('inf')`. Don't know why this isn't documented.

**Comment by hutner700** [comment]
Oh thats work, thanks!

**Comment by gruns** [comment]
created https://github.com/gruns/icecream/issues/90 to avoid `lineWrapWidth` entirely when the terminal width can be determined

**Comment by ranelpadon** [comment]
@alexmojaki looks like this is not working anymore with the latest version?

`ic.lineWrapWidth = 1000`
