### ISSUE TITLE
IC error with class representation broken with unicode

### ISSUE THREAD

**Issue by IVBakker** [gruns/icecream#9]
The following code breaks:
```python
# -*- coding: utf-8 -*-
from icecream import ic
from flask_sqlalchemy import SQLAlchemy
import logging
logging.basicConfig(level='INFO')
db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)

    def __repr__(self):
        return self.name

ic({'a':1}) #WORKS
a=User(name=u'Something ç')
logging.info(a) #WORKS
ic(a) #BREAK
```
With the following output:
```
> python .\test_ice.py
ic| {'a':1}: {'a': 1}
INFO:root:Something ç
Traceback (most recent call last):
  File ".\test_ice.py", line 18, in <module>
    ic(a)
  File "D:\Python27\lib\site-packages\icecream\icecream.py", line 310, in __call__
    icWithArgs(callFrame, icNames, args, self._printOut)
  File "D:\Python27\lib\site-packages\icecream\icecream.py", line 293, in icWithArgs
    output = ', '.join('%s: %r' % (arg, value) for arg, value in pairs)
  File "D:\Python27\lib\site-packages\icecream\icecream.py", line 293, in <genexpr>
    output = ', '.join('%s: %r' % (arg, value) for arg, value in pairs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 10: ordinal not in range(128)
```

I haven't been really down to the problem but I think it's an issue with the representation returning unicode. You should be able to replicate

**Comment by gruns** [comment]
This is indeed a Python 2 issue.

Your code above run in Python v2.7.12.

```
$ python2.7 foo.py 
[("{'a':1}", {'a': 1})]
ic| {'a':1}: {'a': 1}
INFO:root:Something ç
Traceback (most recent call last):
  File "foo.py", line 20, in <module>
    ic(a) #BREAK
  File "/mnt/fett/code/icecream/icecream/icecream.py", line 314, in __call__
    icWithArgs(callFrame, icNames, args, self._printOut)
  File "/mnt/fett/code/icecream/icecream/icecream.py", line 293, in icWithArgs
    print(repr(pairs))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 10: ordinal not in range(128)
```

In Python v3.6.3

```
$ python3.6 foo.py 
[("{'a':1}", {'a': 1})]
ic| {'a':1}: {'a': 1}
INFO:root:Something ç
ic| a: Something ç
```

I'll fix this shortly.

**Comment by IVBakker** [comment]
It would be good to have some try/catch error around sensible areas. So that in the worst case, it doesn't break another project (I've seen unicode errors in SQL Alchemy in Python 2.7 but they aren't blocking)

**Comment by gruns** [comment]
After further digging, this issue is unrelated to IceCream.

```python
#!/usr/bin/env python

class Foo:
    def __repr__(self):
        return u'Something ç'
print(Foo())
```

Yields

```
Traceback (most recent call last):
  File "./foo.py", line 8, in <module>
    print(Foo())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 10: ordinal not in range(128)
```

The problem occurs when `__repr__()` returns a unicode object in Python 2. See

> __repr__() is not really allowed to return Unicode objects in Python 2.x. If
> you do this, you're on your own. The CPython internals try to convert any
> non-str object to a str object, but this is only done to assure that
> PyObject_Repr() always returns a str object.
> 
> I'd suggest closing this as won't fix.

of

  * https://bugs.python.org/issue5876

Is it your code's `__repr__()` that returns a Unicode object? Or SQLAlchemy's?
At first glance, `SQLAlchemy.Model.__repr__()` appears to return a str, not a
Unicode object.

  * https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/model.py#L148

**Comment by IVBakker** [comment]
I see
