### ISSUE TITLE
Clarify timestamp please for ic()

### ISSUE THREAD

**Issue by amogorkon** [gruns/icecream#91]
The behaviour of ic() is badly documented. When I used ic() in a file, I got

`ic| foo.py:323 in bar() at 13:14:14.660`, 
which would have made sense if I was located at UTC, but I'm in Germany with DST, so I wasn't exactly sure what 13:14:14.660 actually meant, even though I suspected a timestamp. So, please either add "UTC+0" or "Z" etc. or make the timestamp timezone-aware.

**Comment by gruns** [comment]
update icecream!

timestamps were UTC in older version of icecream, but were switched to your local timezone to avoid that confusion. they're now created with `datetime.now()`, which is your local time

  * https://docs.python.org/3/library/datetime.html#datetime.datetime.now

see https://github.com/gruns/icecream/blob/master/icecream/icecream.py#L300

**Comment by amogorkon** [comment]
Which version do I need? I only installed icecream via pip, version 2.1.0 apparently..

**Comment by gruns** [comment]
ah. whoops! the local timestamp change hasnt shipped yet

* https://github.com/gruns/icecream/blob/master/changelog.txt#L5

ill ship a new v2.1.1 shortly to fix this for you

**Comment by amogorkon** [comment]
Thanks :)

**Comment by gruns** [comment]
v2.1.1 now live!

update with

```
$ pip install --upgrade icecream
```

**Comment by amogorkon** [comment]
works. 👍
