### ISSUE TITLE
AttributeError: module 'icecream' has no attribute 'configureOutput'

### ISSUE THREAD

**Issue by sezer-muhammed** [gruns/icecream#92]
Hi, I cannot change prefix.

Here my problem:
![image](https://user-images.githubusercontent.com/74321576/123222209-60622000-d4d8-11eb-9c36-6d255c841cd7.png)

**Comment by gruns** [comment]
cant reproduce

```py
#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

from icecream import ic
import time

ic.configureOutput(prefix="deneme")

ic("as")
```

outputs

```
$ ./scratch.py 
deneme"as": 'as'
```

have you updated to the latest icecream? if not, run

```
$ pip install --upgrade icecream
```

**Comment by alexmojaki** [comment]
Use `from icecream import ic`, not `import icecream as ic`.

**Comment by gruns** [comment]
> Use from icecream import ic, not import icecream as ic.

eagle eyes alex 😎
