### ISSUE TITLE
Error: Failed to access the underlying source code for analysis. - a variation.

### ISSUE THREAD

**Issue by patfla** [gruns/icecream#95]
I searched on repl and found a history for this.

I can see that icecream works for ipython, which is nice - but it doesn't appear to work in an elpy buffer in Emacs - which uses ipython.  Elpy is an Emacs mode for editing and running python code.

I suppose icecream needs some kind of screen magic to get the highlighting and that's something that Emacs would support only with difficulty?

Highlighting, from ipython, as seen here:

https://imgur.com/a/fOWKGJD

**Comment by alexmojaki** [comment]
> I searched on repl and found a history for this.

What does this mean?

----

"Error: Failed to access the underlying source code" means the core functionality isn't working. I'm not familiar with emacs but it sounds like elpy is a bit like a REPL/shell, and most REPLs aren't supported. ipython is a special case. Saying that elpy uses ipython is not specific enough.

In the standard shell, the source code of things entered in the shell isn't stored anywhere and can't be retrieved, hence it doesn't show in tracebacks:

```
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

IPython does store the entries, so the source code does show in tracebacks:

```
In [1]: 1/0                                                                                                                                                                                                 
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-1-9e1622b385b6> in <module>
----> 1 1/0

ZeroDivisionError: division by zero
```

If you run `1/0` in elpy, does it show a traceback? Is `1/0` visible somewhere in there?

----

Making coloring/highlighting work is a separate issue from not being able to access source code.

**Comment by patfla** [comment]
> 
> 
> > I searched on repl and found a history for this.
> 
> What does this mean?

I searched Issues in this github for the string repl:

https://github.com/gruns/icecream/issues?q=is%3Aissue+repl

and found issues whose subjects include the same error string I'm seeing.

> 
> "Error: Failed to access the underlying source code" means the core functionality isn't working. I'm not familiar with emacs but it sounds like elpy is a bit like a REPL/shell, and most REPLs aren't supported. ipython is a special case. Saying that elpy uses ipython is not specific enough.
> 
> In the standard shell, the source code of things entered in the shell isn't stored anywhere and can't be retrieved, hence it doesn't show in tracebacks:
> 
> ```
> >>> 1/0
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ZeroDivisionError: division by zero
> ```
> 
> IPython does store the entries, so the source code does show in tracebacks:
> 
> ```
> In [1]: 1/0                                                                                                                                                                                                 
> ---------------------------------------------------------------------------
> ZeroDivisionError                         Traceback (most recent call last)
> <ipython-input-1-9e1622b385b6> in <module>
> ----> 1 1/0
> 
> ZeroDivisionError: division by zero
> ```
> 
> If you run `1/0` in elpy, does it show a traceback? Is `1/0` visible somewhere in there?
> 
> Making coloring/highlighting work is a separate issue from not being able to access source code.

I put only 1/0 into a .py file.  Ran that with python from a cmd then in an elpy buffer in Emacs:

https://imgur.com/a/S6bonii

Error messages look largely the same to me.

**Comment by alexmojaki** [comment]
Can you show a similar comparison and screenshots while trying to use icecream?

**Comment by patfla** [comment]
Well that was interesting

https://imgur.com/a/Hc8vuBR

because it actually worked.

I'll have to back up a bit and figure out what went wrong when I first tried out icecream  Of course, the program I just tested is pretty trivial.

It'd be great if this does work - save me a lot of annoying instrumenting with print statements.  Which of course is the point.

But I guess, at a first iteration.  icecream doesn't necessarily not work in an Emacs elpy environment.

**Comment by patfla** [comment]
Hmm, when I scale it up to where I want to use icecream, I get the following failure:

https://gist.github.com/patfla/e629e2884adc6c4ad55b07fb1a9f96c0

**Comment by alexmojaki** [comment]
Does this happen only when using pdb?

**Comment by patfla** [comment]
Well, that was interesting.  Added an exit() and removed my pdb.set_trace() statement and ic() statements then printed out correctly.  Wonder what that means?  

I use pdb all over the place and while my debugging could move forward 2 steps by using ic(), banning pdb would move me a greater number of steps backward.

https://gist.github.com/patfla/6b3e5e1ff0dae6a900e57f28d3f8b5ca

**Comment by alexmojaki** [comment]
Well it's not banning pdb, it just doesn't work at the same time as pdb. But that is a problem worth fixing and not specific to emacs. Thanks for the report and for your patience narrowing down the problem. I'm closing this in favour of 2 new issues #96 and #97 to make life easier for future readers but feel free to continue the discussion either here or on the new issues.

**Comment by patfla** [comment]
Read those - interesting.  Will be curious to see what the fix is if and when it arrives.  How involved and so on.
