### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by alexmojaki** [gruns/icecream#98]
travis-ci.org is not building any more.

**Comment by palfrey** [comment]
https://app.travis-ci.com/github/gruns/icecream still doesn't appear to have been setup

**Comment by palfrey** [comment]
Any interest in a Github actions setup for this @gruns?

**Comment by alexmojaki** [comment]
I think GHA is a must at this point

**Comment by gruns** [comment]
👍 to GHA over travis. one fewer external tool/implicit dependency

i dont have time to set this up right now. may shortly

**Comment by palfrey** [comment]
> i dont have time to set this up right now. may shortly

Done with https://github.com/gruns/icecream/pull/135
